-module(convert_test).
-include_lib("eunit/include/eunit.hrl").
-include("sbp_message_codes.hrl").

convert_test_() ->
    Realm = <<"test.uri">>,
    Error = <<"wamp.error.test">>,
    Topic = <<"topic.test">>,
    Arg = [1,2,3],
    ArgKw = #{<<"key">> => <<"value">>},
    %% Procedure = <<"test.procedure">>,
    Msgs = [
            {[?HELLO, Realm, #{}],
             #{type => hello, details => #{}, realm => Realm} },
            {[?WELCOME, 234, #{}],
             #{type => welcome, details => #{}, session_id => 234}},
            {[?ABORT, #{}, Error],
             #{type => abort, details => #{}, reason => Error}},
            {[?PUBLISH, 456, #{}, Topic],
             #{type => publish, options => #{}, topic => Topic,
               request_id => 456} },
            {[?PUBLISH, 456, #{}, Topic, Arg],
             #{type => publish, options => #{}, topic => Topic,
               request_id => 456, arguments => Arg }},
            {[?PUBLISH, 456, #{}, Topic, [], ArgKw ],
             #{type => publish, options => #{}, topic => Topic,
               request_id => 456, arguments_kw => ArgKw, arguments => [] } },
            %% {[?PUBLISHED, 123, 456],
            %%  #{type => published, request_id => 123, publication_id => 456}},
            %% {[?SUBSCRIBE, 123, #{}, Topic],
            %%  #{type => subscribe, request_id => 123, options => #{},
            %%    topic => Topic}},
            %% {[?SUBSCRIBED, 123, 456],
            %%  #{type => subscribed, request_id => 123, subscription_id => 456}},
            %% {[?UNSUBSCRIBE, 123, 456],
            %%  #{type => unsubscribe, request_id => 123, subscription_id => 456}},
            %% {[?UNSUBSCRIBED, 123],
            %%  #{type => unsubscribed, request_id => 123}},
            %% {[?EVENT, 456, 789, #{}],
            %%  #{type => event, subscription_id => 456, publication_id => 789,
            %%    details => #{}}},
            %% {[?EVENT, 456, 789, #{}, []],
            %%  #{type => event, subscription_id => 456, publication_id => 789,
            %%    details => #{}, arguments => []}},
            %% {[?EVENT, 456, 789, #{}, [], #{}],
            %%  #{type => event, subscription_id => 456, publication_id => 789,
            %%    details => #{}, arguments => [], arguments_kw => #{}}},
            %% {[?CALL, 123, #{}, Procedure],
            %%  #{type => call, request_id => 123, options => #{},
            %%    procedure => Procedure}},
            %% {[?CALL, 123, #{}, Procedure, []],
            %%  #{type => call, request_id => 123, options => #{},
            %%    procedure => Procedure, arguments => []}},
            %% {[?CALL, 123, #{}, Procedure, [], #{}],
            %%  #{type => call, request_id => 123, options => #{},
            %%    procedure => Procedure, arguments_kw=> #{}, arguments => []}},
            %% {[?RESULT, 123, #{}],
            %%  #{type => result, request_id => 123, details => #{}}},
            %% {[?RESULT, 123, #{}, []],
            %%  #{type => result, request_id => 123, details => #{},
            %%    arguments => []}},
            %% {[?RESULT, 123, #{}, [], #{}],
            %%  #{type => result, request_id => 123, details => #{},
            %%    arguments => [], arguments_kw => #{}}},
            %% {[?REGISTER, 123, #{}, Procedure],
            %%  #{type => register, request_id => 123, options => #{},
            %%    procedure => Procedure}},
            %% {[?REGISTERED, 123, 456],
            %%  #{type => registered, request_id => 123, registration_id => 456}},
            %% {[?UNREGISTER, 123, 456],
            %%  #{type => unregister, request_id => 123, registration_id => 456 }},
            %% {[?UNREGISTERED, 123],
            %%  #{type => unregistered, request_id => 123}},
            %% {[?INVOCATION, 123, 456, #{}],
            %%  #{type => invocation, request_id => 123, registration_id => 456,
            %%   details => #{}}},
            %% {[?INVOCATION, 123, 456, #{}, []],
            %%  #{type => invocation, request_id => 123, registration_id => 456,
            %%   details => #{}, arguments => []}},
            %% {[?INVOCATION, 123, 456, #{}, [], #{}],
            %%  #{type => invocation, request_id => 123, registration_id => 456,
            %%   details => #{}, arguments => [], arguments_kw => #{}}},
            %% {[?YIELD, 123, #{}],
            %%  #{type => yield, request_id => 123, options => #{}}},
            %% {[?YIELD, 123, #{}, []],
            %%  #{type => yield, request_id => 123, options => #{}, arguments => []}},
            %% {[?YIELD, 123, #{}, [], #{}],
            %%  #{type => yield, request_id => 123, options => #{}, arguments => [], arguments_kw => #{}}},
            {[?GOODBYE, #{}, Error],
             #{type => goodbye, details => #{},
               reason => Error }}
           ],
    ToErl = fun({Wamp, Exp}, List) ->
                  [ ?_assertEqual(Exp, sbp_converter:to_erl(Wamp)) | List]
          end,
    ToWamp = fun({Exp, Erl}, List) ->
                  [ ?_assertEqual(Exp, sbp_converter:to_wamp(Erl)) | List]
          end,
    ToErlList = lists:foldl(ToErl, [], Msgs),
    ToWampList = lists:foldl(ToWamp, [], Msgs),
    lists:reverse(ToErlList) ++ lists:reverse(ToWampList).

